# Generated by Django 4.0.5 on 2022-06-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_tg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanel', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
